apiVersion: 1
datasources:
  - name: Prometheus
    uid: PROMETHEUS
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s
    editable: true
  - name: Loki
    uid: LOKI
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    editable: true
