global:
  scrape_interval: 15s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: node-exporter
    static_configs:
      - targets:
          - node-exporter:9100

  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: dcgm-exporter
    static_configs:
      - targets:
          - dcgm-exporter:9400
    relabel_configs:
      - source_labels: [__address__]
        regex: .+
        action: keep

  - job_name: backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - backend:4000
    scheme: http
